# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=32, verbose_name='课程名称')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='课程分类')),
            ],
        ),
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='课程标题')),
                ('course_overview', models.CharField(max_length=128, verbose_name='课程概述')),
                ('scheduling', models.IntegerField(verbose_name='课程学时')),
                ('course_difficulty', models.CharField(max_length=32, verbose_name='课程难度')),
                ('number_of_students_studied', models.IntegerField(verbose_name='已学习人数')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luffycity_course.CourseDetail')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luffycity_course.CourseCategory'),
        ),
    ]
