# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-25 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luffycity_course', '0002_remove_coursedetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='scheduling',
            field=models.IntegerField(null=True, verbose_name='课程学时'),
        ),
    ]
