# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-06 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181006_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beili',
            field=models.IntegerField(default=100),
        ),
    ]
