# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_beili'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.SmallIntegerField(choices=[(0, '立减券'), (1, '满减券'), (2, '折扣券')], default=0, verbose_name='优惠券类型'),
        ),
    ]
