# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-10-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20181008_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='valid_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='有效期（days）'),
        ),
    ]
